### ISSUE TITLE
Masken Billigmasken und FFP2 (ohne Filter) kaufen

### ISSUE THREAD

**Issue by FabianGrote** [FIUS/theo-vorkurs#19]

**Comment by FabianGrote** [comment]
Billigmasken für Erstis falls vergessen kaufen und für jeden Tutor und jede Tutorin 2 bis 3 Masken pro Woche (für beide Vorkurse und für Erstsemestereinführung) kaufen

**Comment by FabianGrote** [comment]
eventuell hat katrin schon masken

**Comment by colfes** [comment]
Katrin kauft. Sollte bis Montag da sein. FFP2 masken für Tutoren und FSler
